package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class historial_proyecto implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "HISTORIAL_PROYECTO_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "HISTORIAL_PROYECTO_ID_GENERATOR", sequenceName = "HISTORIAL_PROYECTO_ID_SEQ")
   private java.lang.Long id;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   private java.util.List<ucuenca.tramitesdiuc.oficio> oficios;

   private java.lang.Boolean oficios_fisicos;

   private java.lang.String observaciones_fisicos;

   private java.lang.Boolean oficios_digitales;

   private java.lang.String directorio;

   private java.lang.String informe_digitales;

   private java.lang.String observaciones_digitales;

   private java.util.Date fecha_historial;

   private java.util.Date fecha_fisicos;

   private java.util.Date fecha_informe_historial;

   public historial_proyecto()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.List<ucuenca.tramitesdiuc.oficio> getOficios()
   {
      return this.oficios;
   }

   public void setOficios(java.util.List<ucuenca.tramitesdiuc.oficio> oficios)
   {
      this.oficios = oficios;
   }

   public java.lang.Boolean getOficios_fisicos()
   {
      return this.oficios_fisicos;
   }

   public void setOficios_fisicos(java.lang.Boolean oficios_fisicos)
   {
      this.oficios_fisicos = oficios_fisicos;
   }

   public java.lang.String getObservaciones_fisicos()
   {
      return this.observaciones_fisicos;
   }

   public void setObservaciones_fisicos(java.lang.String observaciones_fisicos)
   {
      this.observaciones_fisicos = observaciones_fisicos;
   }

   public java.lang.Boolean getOficios_digitales()
   {
      return this.oficios_digitales;
   }

   public void setOficios_digitales(java.lang.Boolean oficios_digitales)
   {
      this.oficios_digitales = oficios_digitales;
   }

   public java.lang.String getDirectorio()
   {
      return this.directorio;
   }

   public void setDirectorio(java.lang.String directorio)
   {
      this.directorio = directorio;
   }

   public java.lang.String getInforme_digitales()
   {
      return this.informe_digitales;
   }

   public void setInforme_digitales(java.lang.String informe_digitales)
   {
      this.informe_digitales = informe_digitales;
   }

   public java.lang.String getObservaciones_digitales()
   {
      return this.observaciones_digitales;
   }

   public void setObservaciones_digitales(
         java.lang.String observaciones_digitales)
   {
      this.observaciones_digitales = observaciones_digitales;
   }

   public java.util.Date getFecha_historial()
   {
      return this.fecha_historial;
   }

   public void setFecha_historial(java.util.Date fecha_historial)
   {
      this.fecha_historial = fecha_historial;
   }

   public java.util.Date getFecha_fisicos()
   {
      return this.fecha_fisicos;
   }

   public void setFecha_fisicos(java.util.Date fecha_fisicos)
   {
      this.fecha_fisicos = fecha_fisicos;
   }

   public java.util.Date getFecha_informe_historial()
   {
      return this.fecha_informe_historial;
   }

   public void setFecha_informe_historial(java.util.Date fecha_informe_historial)
   {
      this.fecha_informe_historial = fecha_informe_historial;
   }

   public historial_proyecto(java.lang.Long id,
         java.util.List<ucuenca.tramitesdiuc.oficio> oficios,
         java.lang.Boolean oficios_fisicos,
         java.lang.String observaciones_fisicos,
         java.lang.Boolean oficios_digitales, java.lang.String directorio,
         java.lang.String informe_digitales,
         java.lang.String observaciones_digitales,
         java.util.Date fecha_historial, java.util.Date fecha_fisicos,
         java.util.Date fecha_informe_historial)
   {
      this.id = id;
      this.oficios = oficios;
      this.oficios_fisicos = oficios_fisicos;
      this.observaciones_fisicos = observaciones_fisicos;
      this.oficios_digitales = oficios_digitales;
      this.directorio = directorio;
      this.informe_digitales = informe_digitales;
      this.observaciones_digitales = observaciones_digitales;
      this.fecha_historial = fecha_historial;
      this.fecha_fisicos = fecha_fisicos;
      this.fecha_informe_historial = fecha_informe_historial;
   }

}