package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class informe_final implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "INFORME_FINAL_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "INFORME_FINAL_ID_GENERATOR", sequenceName = "INFORME_FINAL_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String informe_final;

   private java.lang.String observaciones;

   public informe_final()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getInforme_final()
   {
      return this.informe_final;
   }

   public void setInforme_final(java.lang.String informe_final)
   {
      this.informe_final = informe_final;
   }

   public java.lang.String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(java.lang.String observaciones)
   {
      this.observaciones = observaciones;
   }

   public informe_final(java.lang.Long id, java.lang.String informe_final,
         java.lang.String observaciones)
   {
      this.id = id;
      this.informe_final = informe_final;
      this.observaciones = observaciones;
   }

}