package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class miembro implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "MIEMBRO_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "MIEMBRO_ID_GENERATOR", sequenceName = "MIEMBRO_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String tipo_documento;

   private java.lang.String nro_documento;

   private java.lang.String nombres;

   private java.lang.String correo_personal;

   private java.lang.String correo_institucional;

   private java.lang.String cargo;

   private java.lang.String afiliacion;

   private java.lang.String facultad;

   private java.lang.String escuela;

   private java.lang.String RUC;

   private java.lang.String ubicacion;

   private java.lang.String tipo_institucion;

   private java.util.Date fecha_inicio;

   private java.util.Date fecha_fin;

   private java.lang.String aporte_cientifico;

   private java.lang.String actividades_consideradas;

   private java.lang.String actividades_no_consideradas;

   private java.lang.Integer dedicacion;

   public miembro()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getTipo_documento()
   {
      return this.tipo_documento;
   }

   public void setTipo_documento(java.lang.String tipo_documento)
   {
      this.tipo_documento = tipo_documento;
   }

   public java.lang.String getNro_documento()
   {
      return this.nro_documento;
   }

   public void setNro_documento(java.lang.String nro_documento)
   {
      this.nro_documento = nro_documento;
   }

   public java.lang.String getNombres()
   {
      return this.nombres;
   }

   public void setNombres(java.lang.String nombres)
   {
      this.nombres = nombres;
   }

   public java.lang.String getCorreo_personal()
   {
      return this.correo_personal;
   }

   public void setCorreo_personal(java.lang.String correo_personal)
   {
      this.correo_personal = correo_personal;
   }

   public java.lang.String getCorreo_institucional()
   {
      return this.correo_institucional;
   }

   public void setCorreo_institucional(java.lang.String correo_institucional)
   {
      this.correo_institucional = correo_institucional;
   }

   public java.lang.String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(java.lang.String cargo)
   {
      this.cargo = cargo;
   }

   public java.lang.String getAfiliacion()
   {
      return this.afiliacion;
   }

   public void setAfiliacion(java.lang.String afiliacion)
   {
      this.afiliacion = afiliacion;
   }

   public java.lang.String getFacultad()
   {
      return this.facultad;
   }

   public void setFacultad(java.lang.String facultad)
   {
      this.facultad = facultad;
   }

   public java.lang.String getEscuela()
   {
      return this.escuela;
   }

   public void setEscuela(java.lang.String escuela)
   {
      this.escuela = escuela;
   }

   public java.lang.String getRUC()
   {
      return this.RUC;
   }

   public void setRUC(java.lang.String RUC)
   {
      this.RUC = RUC;
   }

   public java.lang.String getUbicacion()
   {
      return this.ubicacion;
   }

   public void setUbicacion(java.lang.String ubicacion)
   {
      this.ubicacion = ubicacion;
   }

   public java.lang.String getTipo_institucion()
   {
      return this.tipo_institucion;
   }

   public void setTipo_institucion(java.lang.String tipo_institucion)
   {
      this.tipo_institucion = tipo_institucion;
   }

   public java.util.Date getFecha_inicio()
   {
      return this.fecha_inicio;
   }

   public void setFecha_inicio(java.util.Date fecha_inicio)
   {
      this.fecha_inicio = fecha_inicio;
   }

   public java.util.Date getFecha_fin()
   {
      return this.fecha_fin;
   }

   public void setFecha_fin(java.util.Date fecha_fin)
   {
      this.fecha_fin = fecha_fin;
   }

   public java.lang.String getAporte_cientifico()
   {
      return this.aporte_cientifico;
   }

   public void setAporte_cientifico(java.lang.String aporte_cientifico)
   {
      this.aporte_cientifico = aporte_cientifico;
   }

   public java.lang.String getActividades_consideradas()
   {
      return this.actividades_consideradas;
   }

   public void setActividades_consideradas(
         java.lang.String actividades_consideradas)
   {
      this.actividades_consideradas = actividades_consideradas;
   }

   public java.lang.String getActividades_no_consideradas()
   {
      return this.actividades_no_consideradas;
   }

   public void setActividades_no_consideradas(
         java.lang.String actividades_no_consideradas)
   {
      this.actividades_no_consideradas = actividades_no_consideradas;
   }

   public java.lang.Integer getDedicacion()
   {
      return this.dedicacion;
   }

   public void setDedicacion(java.lang.Integer dedicacion)
   {
      this.dedicacion = dedicacion;
   }

   public miembro(java.lang.Long id, java.lang.String tipo_documento,
         java.lang.String nro_documento, java.lang.String nombres,
         java.lang.String correo_personal,
         java.lang.String correo_institucional, java.lang.String cargo,
         java.lang.String afiliacion, java.lang.String facultad,
         java.lang.String escuela, java.lang.String RUC,
         java.lang.String ubicacion, java.lang.String tipo_institucion,
         java.util.Date fecha_inicio, java.util.Date fecha_fin,
         java.lang.String aporte_cientifico,
         java.lang.String actividades_consideradas,
         java.lang.String actividades_no_consideradas,
         java.lang.Integer dedicacion)
   {
      this.id = id;
      this.tipo_documento = tipo_documento;
      this.nro_documento = nro_documento;
      this.nombres = nombres;
      this.correo_personal = correo_personal;
      this.correo_institucional = correo_institucional;
      this.cargo = cargo;
      this.afiliacion = afiliacion;
      this.facultad = facultad;
      this.escuela = escuela;
      this.RUC = RUC;
      this.ubicacion = ubicacion;
      this.tipo_institucion = tipo_institucion;
      this.fecha_inicio = fecha_inicio;
      this.fecha_fin = fecha_fin;
      this.aporte_cientifico = aporte_cientifico;
      this.actividades_consideradas = actividades_consideradas;
      this.actividades_no_consideradas = actividades_no_consideradas;
      this.dedicacion = dedicacion;
   }

}