package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class oficio implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "OFICIO_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "OFICIO_ID_GENERATOR", sequenceName = "OFICIO_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String nro_oficio;

   private java.lang.String nro_tramite;

   private java.util.Date fecha_oficio;

   private java.lang.String codigo_ubicacion;

   private java.lang.String observaciones;

   private java.lang.String director_solicitante;

   public oficio()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getNro_oficio()
   {
      return this.nro_oficio;
   }

   public void setNro_oficio(java.lang.String nro_oficio)
   {
      this.nro_oficio = nro_oficio;
   }

   public java.lang.String getNro_tramite()
   {
      return this.nro_tramite;
   }

   public void setNro_tramite(java.lang.String nro_tramite)
   {
      this.nro_tramite = nro_tramite;
   }

   public java.util.Date getFecha_oficio()
   {
      return this.fecha_oficio;
   }

   public void setFecha_oficio(java.util.Date fecha_oficio)
   {
      this.fecha_oficio = fecha_oficio;
   }

   public java.lang.String getCodigo_ubicacion()
   {
      return this.codigo_ubicacion;
   }

   public void setCodigo_ubicacion(java.lang.String codigo_ubicacion)
   {
      this.codigo_ubicacion = codigo_ubicacion;
   }

   public java.lang.String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(java.lang.String observaciones)
   {
      this.observaciones = observaciones;
   }

   public java.lang.String getDirector_solicitante()
   {
      return this.director_solicitante;
   }

   public void setDirector_solicitante(java.lang.String director_solicitante)
   {
      this.director_solicitante = director_solicitante;
   }

   public oficio(java.lang.Long id, java.lang.String nro_oficio,
         java.lang.String nro_tramite, java.util.Date fecha_oficio,
         java.lang.String codigo_ubicacion, java.lang.String observaciones,
         java.lang.String director_solicitante)
   {
      this.id = id;
      this.nro_oficio = nro_oficio;
      this.nro_tramite = nro_tramite;
      this.fecha_oficio = fecha_oficio;
      this.codigo_ubicacion = codigo_ubicacion;
      this.observaciones = observaciones;
      this.director_solicitante = director_solicitante;
   }

}