package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class presupuesto implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "PRESUPUESTO_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "PRESUPUESTO_ID_GENERATOR", sequenceName = "PRESUPUESTO_ID_SEQ")
   private java.lang.Long id;

   @javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = { javax.persistence.CascadeType.ALL })
   private java.util.List<ucuenca.tramitesdiuc.rubro> rubros;

   private java.lang.String justificacion;

   public presupuesto()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.List<ucuenca.tramitesdiuc.rubro> getRubros()
   {
      return this.rubros;
   }

   public void setRubros(java.util.List<ucuenca.tramitesdiuc.rubro> rubros)
   {
      this.rubros = rubros;
   }

   public java.lang.String getJustificacion()
   {
      return this.justificacion;
   }

   public void setJustificacion(java.lang.String justificacion)
   {
      this.justificacion = justificacion;
   }

   public presupuesto(java.lang.Long id,
         java.util.List<ucuenca.tramitesdiuc.rubro> rubros,
         java.lang.String justificacion)
   {
      this.id = id;
      this.rubros = rubros;
      this.justificacion = justificacion;
   }

}