package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class prorroga implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "PRORROGA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "PRORROGA_ID_GENERATOR", sequenceName = "PRORROGA_ID_SEQ")
   private java.lang.Long id;

   private java.util.Date fecha_final;

   private java.lang.String justificacion;

   private java.lang.Integer duracion;

   public prorroga()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getFecha_final()
   {
      return this.fecha_final;
   }

   public void setFecha_final(java.util.Date fecha_final)
   {
      this.fecha_final = fecha_final;
   }

   public java.lang.String getJustificacion()
   {
      return this.justificacion;
   }

   public void setJustificacion(java.lang.String justificacion)
   {
      this.justificacion = justificacion;
   }

   public java.lang.Integer getDuracion()
   {
      return this.duracion;
   }

   public void setDuracion(java.lang.Integer duracion)
   {
      this.duracion = duracion;
   }

   public prorroga(java.lang.Long id, java.util.Date fecha_final,
         java.lang.String justificacion, java.lang.Integer duracion)
   {
      this.id = id;
      this.fecha_final = fecha_final;
      this.justificacion = justificacion;
      this.duracion = duracion;
   }

}