package ucuenca.tramitesdiuc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class tramite implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "TRAMITE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "TRAMITE_ID_GENERATOR", sequenceName = "TRAMITE_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String solicitante;

   private java.lang.String convocatoria;

   private java.lang.Integer nro_tramite;

   private java.util.Date fecha_solicitud;

   private java.lang.String titulo_proyecto;

   private java.lang.String telefono_contacto;

   private java.lang.String codigo_proyecto;

   private java.lang.String observaciones_validacion;

   private java.lang.String observaciones_aprobacion;

   public tramite()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getSolicitante()
   {
      return this.solicitante;
   }

   public void setSolicitante(java.lang.String solicitante)
   {
      this.solicitante = solicitante;
   }

   public java.lang.String getConvocatoria()
   {
      return this.convocatoria;
   }

   public void setConvocatoria(java.lang.String convocatoria)
   {
      this.convocatoria = convocatoria;
   }

   public java.lang.Integer getNro_tramite()
   {
      return this.nro_tramite;
   }

   public void setNro_tramite(java.lang.Integer nro_tramite)
   {
      this.nro_tramite = nro_tramite;
   }

   public java.util.Date getFecha_solicitud()
   {
      return this.fecha_solicitud;
   }

   public void setFecha_solicitud(java.util.Date fecha_solicitud)
   {
      this.fecha_solicitud = fecha_solicitud;
   }

   public java.lang.String getTitulo_proyecto()
   {
      return this.titulo_proyecto;
   }

   public void setTitulo_proyecto(java.lang.String titulo_proyecto)
   {
      this.titulo_proyecto = titulo_proyecto;
   }

   public java.lang.String getTelefono_contacto()
   {
      return this.telefono_contacto;
   }

   public void setTelefono_contacto(java.lang.String telefono_contacto)
   {
      this.telefono_contacto = telefono_contacto;
   }

   public java.lang.String getCodigo_proyecto()
   {
      return this.codigo_proyecto;
   }

   public void setCodigo_proyecto(java.lang.String codigo_proyecto)
   {
      this.codigo_proyecto = codigo_proyecto;
   }

   public java.lang.String getObservaciones_validacion()
   {
      return this.observaciones_validacion;
   }

   public void setObservaciones_validacion(
         java.lang.String observaciones_validacion)
   {
      this.observaciones_validacion = observaciones_validacion;
   }

   public java.lang.String getObservaciones_aprobacion()
   {
      return this.observaciones_aprobacion;
   }

   public void setObservaciones_aprobacion(
         java.lang.String observaciones_aprobacion)
   {
      this.observaciones_aprobacion = observaciones_aprobacion;
   }

   public tramite(java.lang.Long id, java.lang.String solicitante,
         java.lang.String convocatoria, java.lang.Integer nro_tramite,
         java.util.Date fecha_solicitud, java.lang.String titulo_proyecto,
         java.lang.String telefono_contacto, java.lang.String codigo_proyecto,
         java.lang.String observaciones_validacion,
         java.lang.String observaciones_aprobacion)
   {
      this.id = id;
      this.solicitante = solicitante;
      this.convocatoria = convocatoria;
      this.nro_tramite = nro_tramite;
      this.fecha_solicitud = fecha_solicitud;
      this.titulo_proyecto = titulo_proyecto;
      this.telefono_contacto = telefono_contacto;
      this.codigo_proyecto = codigo_proyecto;
      this.observaciones_validacion = observaciones_validacion;
      this.observaciones_aprobacion = observaciones_aprobacion;
   }

}